name: "Buildroot + Rauc + Edgehog RaspberryPi4 Image Release"
on:
  push:
    tags:
      - '*'

jobs:
  build-rpi-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libudev-dev libsystemd-dev bmap-tools
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.58.1
          override: true
      - name: Checkout buildroot
        run: git clone --depth 1 --branch 2022.02.x --no-single-branch https://git.busybox.net/buildroot/ $GITHUB_WORKSPACE/buildroot      
      - name: Checkout br2rauc
        uses: actions/checkout@v3
        with:
          repository: edgehog-device-manager/br2rauc
          path: ./br2rauc
      - name: Check out edgehog-buildroot-packages
        uses: actions/checkout@v3
        with:
          repository: edgehog-device-manager/edgehog-buildroot-packages
          path: ./edgehog-buildroot-packages     
      - name: Build image
        run: |        
          mkdir output
          mkdir artifact
          ( cd br2rauc/ ; ./openssl-ca.sh )
          ./buildroot/support/kconfig/merge_config.sh -O output -m \
          br2rauc/configs/raspberrypi4-64-rauc_defconfig edgehog-buildroot-packages/configs/edgehog_device_runtime_defconfig                                             
          make -C buildroot/ BR2_EXTERNAL=../br2rauc:../edgehog-buildroot-packages O=../output olddefconfig
          cd output && make          
          cp images/sdcard.img.xz images/update.raucb images/sdcard.img.bmap ../artifact/
          echo "release_date=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Compress image
        run: |        
          tar -zcvf BR2-RAUC-EDGEHOG-${{ env.release_date }}.tar.gz artifact        
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: BR2-RAUC-EDGEHOG-${{ env.release_date }}.tar.gz
          fail_on_unmatched_files: true    
